interface ExtensionsMap {
    [extension: string]: string;
}

export const Languages = [
    { name: "ABAP", extensions: [".abap"] },
    { name: "Apex", extensions: [".apex"] },
    { name: "AZCLI", extensions: [".azcli"] },
    { name: "Bat", extensions: [".bat"] },
    { name: "Bicep", extensions: [".bicep"] },
    { name: "Cameligo", extensions: [".cameligo"] },
    { name: "Clojure", extensions: [".clj"] },
    { name: "CoffeeScript", extensions: [".coffee"] },
    { name: "C", extensions: [".c", ".h"] },
    { name: "CPP", extensions: [".cpp", ".hpp"] },
    { name: "CSharp", extensions: [".cs"] },
    { name: "CSP", extensions: [".csp"] },
    { name: "CSS", extensions: [".css"] },
    { name: "Cypher", extensions: [".cypher"] },
    { name: "Dart", extensions: [".dart"] },
    { name: "Dockerfile", extensions: [".dockerfile"] },
    { name: "ECL", extensions: [".ecl"] },
    { name: "Elixir", extensions: [".ex"] },
    { name: "Flow9", extensions: [".f9"] },
    { name: "F#", extensions: [".fs"] },
    { name: "FreeMarker", extensions: [".ftl"] },
    { name: "Go", extensions: [".go"] },
    { name: "GraphQL", extensions: [".graphql"] },
    { name: "Handlebars", extensions: [".hbs"] },
    { name: "HCL", extensions: [".hcl"] },
    { name: "HTML", extensions: [".html"] },
    { name: "INI", extensions: [".ini"] },
    { name: "Java", extensions: [".java"] },
    { name: "JavaScript", extensions: [".js", ".jsx", ".mjs"] },
    { name: "Julia", extensions: [".jl"] },
    { name: "Kotlin", extensions: [".kt"] },
    { name: "LESS", extensions: [".less"] },
    { name: "Lexon", extensions: [".lx"] },
    { name: "Lua", extensions: [".lua"] },
    { name: "Liquid", extensions: [".liquid"] },
    { name: "M3", extensions: [".m3"] },
    { name: "Markdown", extensions: [".md"] },
    { name: "MIPS", extensions: [".s"] },
    { name: "MSDAX", extensions: [".msdax"] },
    { name: "MySQL", extensions: [".mysql"] },
    { name: "Objective-C", extensions: [".m"] },
    { name: "Pascal", extensions: [".pas"] },
    { name: "Pascaligo", extensions: [".ligo"] },
    { name: "Perl", extensions: [".pl"] },
    { name: "PGSQL", extensions: [".pgsql"] },
    { name: "PHP", extensions: [".php"] },
    { name: "PLA", extensions: [".pla"] },
    { name: "Postiats", extensions: [".dats"] },
    { name: "PowerQuery", extensions: [".pq"] },
    { name: "PowerShell", extensions: [".ps1"] },
    { name: "ProtoBuf", extensions: [".proto"] },
    { name: "Pug", extensions: [".pug"] },
    { name: "Python", extensions: [".py"] },
    { name: "QSharp", extensions: [".qs"] },
    { name: "R", extensions: [".r"] },
    { name: "Razor", extensions: [".cshtml"] },
    { name: "Redis", extensions: [".redis"] },
    { name: "Redshift", extensions: [".redshift"] },
    { name: "reStructuredText", extensions: [".rst"] },
    { name: "Ruby", extensions: [".rb"] },
    { name: "Rust", extensions: [".rs"] },
    { name: "SB", extensions: [".sb"] },
    { name: "Scala", extensions: [".scala"] },
    { name: "Scheme", extensions: [".scm"] },
    { name: "SCSS", extensions: [".scss"] },
    { name: "Shell", extensions: [".sh"] },
    { name: "Solidity", extensions: [".sol"] },
    { name: "Sophia", extensions: [".aes"] },
    { name: "SPARQL", extensions: [".sparql"] },
    { name: "SQL", extensions: [".sql"] },
    { name: "ST", extensions: [".st", ".iecst", ".iecplc", ".lc3lib"] },
    { name: "Swift", extensions: [".swift"] },
    { name: "SystemVerilog", extensions: [".sv"] },
    { name: "Tcl", extensions: [".tcl"] },
    { name: "Twig", extensions: [".twig"] },
    { name: "TypeScript", extensions: [".ts", ".tsx"] },
    { name: "VB", extensions: [".vb"] },
    { name: "WebGPU Shading Language", extensions: [".wgsl"] },
    { name: "XML", extensions: [".xml"] },
    { name: "YAML", extensions: [".yaml", ".yml"] }
];
